module.exports = {
  AMOUNT_PAID: {
    PAID: "Paid",
    NOT_PAID: "Not Paid",
    PENDING: "Pending",
  },
  PAYMENT_METHOD: {
    GPAY: "gpay",
    PHONEPE: "phonepe",
    PAYTM: "paytm",
  },
  OTP_TYPE: {
    FORGOT_PASSWORD: "forgotPassword",
  },
  TIME_UNITS: {
    SECONDS: "seconds",
  },
  NUMBERS_DIGITS_UNITS: {
    TEENS: [
      "",
      "One ",
      "Two ",
      "Three ",
      "Four ",
      "Five ",
      "Six ",
      "Seven ",
      "Eight ",
      "Nine ",
      "Ten ",
      "Eleven ",
      "Twelve ",
      "Thirteen ",
      "Fourteen ",
      "Fifteen ",
      "Sixteen ",
      "Seventeen ",
      "Eighteen ",
      "Nineteen ",
    ],
    TENS: [
      "",
      "",
      "Twenty",
      "Thirty",
      "Forty",
      "Fifty",
      "Sixty",
      "Seventy",
      "Eighty",
      "Ninety",
    ],
  },
};
